[package]
name = "rolidris/rolidris"
version = "0.1.0"
authors = []

[dependencies]
"ziman/lightyear" = { git = "https://github.com/appositum/lightyear" }

[targets.lib]
path = "src"
mods = [
  "Rolidris",
  "Rolidris.Parser",
  "Rolidris.Syntax"
]
idris_opts = ["-p", "contrib"]

[[targets.bin]]
name = "rolidris"
path = "src"
main = "Main"
idris_opts = ["-p", "contrib"]
